const raffle = require('./raffle');
const dotenv = require('dotenv').config();

const MersenneTwister = require('./mersenne-twister');
const weightedSelection = require('./weighted-selection');
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider(`https://mainnet.infura.io/v3/${process.env.WEB3_INFURA_PROJECT_ID}`))

// // Generate a collection of participants whose likelihood are generated by random function 'genrand_int31'
// seed = 10;
// const numberOfParticipants = 1000;
// const m = new MersenneTwister(seed);
// likelihoods = []
// for (step=0;step<numberOfParticipants;step++){
//   likelihoods[step] = m.genrand_int31();
// }

// // Now call the 'wei
// winners = weightedSelection(1,likelihoods,30);
// console.log(winners);


let contractAddress = '0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85';
contractAddress = web3.utils.toChecksumAddress(contractAddress);

raffle(contractAddress);
